version: "3.8"

name: js-app
services:
    db:
      build:
        context: .
        dockerfile: Dockerfile.mongo
    redis:
      build:
        context: .
        dockerfile: Dockerfile.redis
    api:
        build:
            context: services
            dockerfile: Dockerfile
    web:
        build:
            context: client
            dockerfile: Dockerfile
        ports:
            - "8099:3000"
        expose:
            - 80